# Generated by Django 4.2.17 on 2025-01-08 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Logo',
        ),
    ]
