# Generated by Django 4.2.20 on 2025-05-06 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.AlterModelOptions(
            name='digitalmedia',
            options={'verbose_name': 'Digital Media', 'verbose_name_plural': 'Digital Media'},
        ),
        migrations.AlterModelOptions(
            name='journal',
            options={'verbose_name': 'Journal', 'verbose_name_plural': 'Journals'},
        ),
    ]
