# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: greet.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'greet.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bgreet.proto\x12\x05greet\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\" \n\rHelloResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1b\n\x0b\x41likRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1f\n\x0c\x41likResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2E\n\x0cHelloService\x12\x35\n\x08SayHello\x12\x13.greet.HelloRequest\x1a\x14.greet.HelloResponse2A\n\x0b\x41likService\x12\x32\n\x07SayAlik\x12\x12.greet.AlikRequest\x1a\x13.greet.AlikResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'greet_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HELLOREQUEST']._serialized_start=22
  _globals['_HELLOREQUEST']._serialized_end=50
  _globals['_HELLORESPONSE']._serialized_start=52
  _globals['_HELLORESPONSE']._serialized_end=84
  _globals['_ALIKREQUEST']._serialized_start=86
  _globals['_ALIKREQUEST']._serialized_end=113
  _globals['_ALIKRESPONSE']._serialized_start=115
  _globals['_ALIKRESPONSE']._serialized_end=146
  _globals['_HELLOSERVICE']._serialized_start=148
  _globals['_HELLOSERVICE']._serialized_end=217
  _globals['_ALIKSERVICE']._serialized_start=219
  _globals['_ALIKSERVICE']._serialized_end=284
# @@protoc_insertion_point(module_scope)
